-- -- ENCODING -> UTF-8 etc.
-- local function encoding()
--     local fileencoding = vim.opt.fileencoding:get()
--     if fileencoding == nil then
--     -- if fileencoding == "nil" then
--         fileencoding = ""
--     end
--     -- return fileencoding ~= "" and string.format("%s", encoding) or ""
--     return tostring(fileencoding)
-- end

-- function StatuslineRender()
--   ---@diagnostic disable-next-line: param-type-mismatch
--   return table.concat({
--     vim.fn.expand("%"),
--     " ",
--     "pepe",
--   })
-- end
--
-- vim.o.statusline = "%!v:lua.StatuslineRender()"

-- vim.keymap.set({ "n", "v" }, "<leader>F", function()
--   local clients = vim.lsp.get_clients({
--     method = "textDocument/format",
--   })
--
--   if #clients > 0 then
--     vim.lsp.buf.format()
--   else
--     print("no formatter :(")
--   end
-- end, { desc = "LSP formatting" })
--

-- vim.keymap.set("n", "<leader>L", function ()
--   require("telescope.builtin").find_files({
--     cwd = "/run"
--   })
-- end)

