return {
  "nvzone/showkeys",
  cmd = "ShowkeysToggle",
  keys = {
    { "<leader>sk", "<cmd>ShowkeysToggle<CR>", desc = "[Show-keys] Toggle" },
  },
  opts = {
    -- position = "bottom-right",
    timeout = 3,
    maxkeys = 10,
    show_count = true,
    excluded_modes = { "i" },
    position = "top-left",
    winopts = {
      focusable = false,
      relative = "editor",
      border = "rounded",
      height = 1,
      row = 0,
      col = 0,
    },
    keyformat = {
      ["<BS>"] = "󰁮 ",
      ["<CR>"] = "󰘌",
      ["<Space>"] = "󱁐",
      ["<Up>"] = "󰁝",
      ["<Down>"] = "󰁅",
      ["<Left>"] = "󰁍",
      ["<Right>"] = "󰁔",
      ["k"] = "󰁝[k]",
      ["j"] = "󰁅[j]",
      ["h"] = "󰁍[h]",
      ["l"] = "󰁔[l]",
      ["<PageUp>"] = "Pg-Up",
      ["<PageDown>"] = "Pg-Down",
      ["<M>"] = "Alt",
      ["<C>"] = "Ctrl",
    },
  },
}
